### PR TITLE
64 bits compatibility and fixed grammar/spelling mistakes

### PR DESCRIPTION
**Pull request by trk305**
Fixed source code compilation error with 64 bits platform (now DWORD_PTR to handle both pointer size for 32 bits and 64 bits)

also grammar/spelling mistakes has been fixed.

### CODE REVIEW

**Review by Leo40Git — APPROVED** [review]
LGTM, will merge now and test a new release tomorrow.

**Comment by trk305** [comment]
> LGTM, will merge now and test a new release tomorrow.


Any updates?

**Comment by Leo40Git** [comment]
time is a social construct

https://github.com/Leo40Git/SteamPriorityLauncher/releases/tag/1.4

**Comment by trk305** [comment]
> time is a social construct
> 
> https://github.com/Leo40Git/SteamPriorityLauncher/releases/tag/1.4

Sorry for disturbance :( my mistake.

**Pull request merged**
